#%RAML 1.0
---
title: SIP+
baseUri: https://{sipPlusServer}:9000
version: v1
documentation:
  - title: Introduccion  
    content: |
      Documentación de la API de SIP+. 

      Para realizar pruebas se puede utilizar Postman. Para autenticación se debe seleccionar `Authorization -> Basic Auth` e incluir un Usuario y Password de SipPlus.

  - title: Documentación oficial
    content: |
      Para ver el diccionario de SIP+ (significado de cada código) visitar [dictionary.js](http://www.sipplus.org/fromDocs/dictionary.js).

      Para ver la documentación oficial de los WebServices visitar [Wes services provistos por Sip+](http://www.sipplus.org/fromDocs/webservices-provided.html).


/record/AR:
  /{tipoDocumento}:
    uriParameters:
      tipoDocumento:
        description: "Tipo de documento (DNI/OTR)"
        type: "string"
    /{numero}:
      description: ""
      uriParameters:
        numero:
          description: "Numero de documento"
          type: "string"
      get: # HTTP method declaration
        description: Obtener los datos de un paciente. Ejemplo GET {baseUri}/record/AR/DNI/12345678
        queryParameters:
          basic_auth:
            displayName: "Basic Auth"
            type: string
            description: "user:password"
            required: true
        responses: # declare a response
          200: # HTTP status code
            body: # declare content of response
              application/json: # media type
                example: | # structural definition of a response (schema or type)
                  {
                    "1018": "País de identificación (text)",
                    "1019": "Tipo de identificación (text)",
                    "0001": "Nombre (text)",
                    "pregnancies": {
                      "5": {
                        "children": {
                          "1": {
                            "0299": "Ligadura cordón (enumeration) ['< 1 min.','1 a 3 min.','< 30 seg.','30 seg. a 1 min.','> 1 min.','> 3 min.']",
                            "0449": "Inmunización Hepatitis B (enumeration) ['no','si','n/c']",
                            "0447": "RN Tamizaje - Chagas (enumeration) ['-','+','no se hizo']",
                            "0412": "TTO. VDRL (enumeration) ['no','si','n/c','s/d']",
                            "0446": "RN Tamizaje - Audición (enumeration) ['-','+','no se hizo']",
                            "0640": "Lactancia materna inicio precoz (enumeration) ['no','si','n/c']",
                            "0441": "VIH en RN - Tratamiento (enumeration) ['no','si','n/c','s/d']",
                            "0445": "RN Reanimación - Medicación (enumeration) ['no','si']",
                            "0297": "Placenta completa (enumeration) ['no','si']",
                            "0286": "Embarazo múltiple - orden (numeric)",
                            "0321": "Apgar 1er. Minuto (numeric)",
                            "0375": "Edad  < 1 dia (boolean)",
                            "0347": "RN Tamizaje - Toxo IgM (enumeration) ['-','+','no se hizo']",
                            "0290": "Código operatorio (code)",
                            "0310": "RN Sexo (enumeration) ['femenino','masculino','no definido']",
                            "0325": "RN Reanimación - Máscara (enumeration) ['no','si']",
                            "0378": "BCG (enumeration) ['no','si']",
                            "0336": "Enfermedades RN (enumeration) ['1 o más','ninguna']",
                            "0395": "Peso RN al egreso (numeric)",
                            "0343": "RN Tamizaje - VDRL (enumeration) ['-','+','no se hizo']",
                            "0283": "Hora nacimiento (time)",
                            "0329": "Fallece lugar de parto (enumeration) ['no','si']",
                            "0370": "Egreso RN - hora (time)",
                            "0320": "RN Peso para Edad Gestacional (enumeration) ['adecuado','pequeño','grande']",
                            "0371": "Egreso RN (enumeration) ['vivo','fallece','traslado']",
                            "0282": "Nacimiento (enumeration) ['vivio','muerto ante parto','muerto parto','muerto ignora momento']",
                            "0377": "Boca arriba (enumeration) ['no','si']",
                            "0293": "Desgarros (no) (boolean)",
                            "0425": "Egreso RN - fecha (date)",
                            "0331": "Atendió Parto (enumeration) ['medico','obstetra','enfermera','auxiliar','estudiante','empirica','otro','pediatra']",
                            "0346": "RN Tamizaje - Bilirrubina (enumeration) ['-','+','no se hizo']",
                            "0335": "Defectos congénitos (enumeration) ['no','menor','mayor','si']",
                            "0324": "RN Reanimación - Aspiración (enumeration) ['no','si']",
                            "0313": "Perimetro cefálico (numeric)",
                            "0327": "RN Reanimación - Masaje (enumeration) ['no','si']",
                            "0376": "Alimento al alta (enumeration) ['lactancia exclusiva','parcial','artificial']",
                            "0296": "Ocitócicos postalumbramiento (enumeration) ['no','si']",
                            "0323": "RN Reanimación - Estimulación (enumeration) ['no','si']",
                            "0316": "Edad gestacional RN - días (numeric)",
                            "0292": "Episiotomía (enumeration) ['no','si']",
                            "0388": "Nro. Historia RN (text)",
                            "0298": "Placenta retenida (enumeration) ['no','si']",
                            "0287": "Terminación (enumeration) ['vaginal espontánea','cesárea','fórceps','vacuum','otra']",
                            "0291": "Posición parto (enumeration) ['sentada','cuclillas','acostada']",
                            "0333": "Atendió Neonato (enumeration) ['medico','obstetra','enfermera','auxiliar','estudiante','empirica','otro','pediatra']",
                            "0326": "RN Reanimación - Oxígeno (enumeration) ['no','si']",
                            "0348": "RN Tamizaje - Meconio 1er. día (enumeration) ['no','si']",
                            "0311": "Peso al nacer (numeric)",
                            "0322": "Apgar 5to. Minuto (numeric)",
                            "0315": "Edad gestacional RN (numeric)",
                            "0330": "Referido (enumeration) ['alojamiento conjunto','neonatología','otro hospital']",
                            "0284": "Fecha de nacimiento (date)",
                            "0389": "Nombre RN (text)",
                            "0373": "Fallece lugar de traslado (enumeration) ['no','si','sin dato']",
                            "0295": "Ocitócicos prealumbramiento (enumeration) ['no','si']",
                            "0328": "RN Reanimación - Tubo (enumeration) ['no','si']"
                          },
                          "2": {
                            "0299": "Ligadura cordón (enumeration) ['< 1 min.','1 a 3 min.','< 30 seg.','30 seg. a 1 min.','> 1 min.','> 3 min.']",
                            "0449": "Inmunización Hepatitis B (enumeration) ['no','si','n/c']",
                            "0447": "RN Tamizaje - Chagas (enumeration) ['-','+','no se hizo']",
                            "0412": "TTO. VDRL (enumeration) ['no','si','n/c','s/d']",
                            "0446": "RN Tamizaje - Audición (enumeration) ['-','+','no se hizo']",
                            "0640": "Lactancia materna inicio precoz (enumeration) ['no','si','n/c']",
                            "0441": "VIH en RN - Tratamiento (enumeration) ['no','si','n/c','s/d']",
                            "0445": "RN Reanimación - Medicación (enumeration) ['no','si']",
                            "0297": "Placenta completa (enumeration) ['no','si']",
                            "0286": "Embarazo múltiple - orden (numeric)",
                            "0321": "Apgar 1er. Minuto (numeric)",
                            "0375": "Edad  < 1 dia (boolean)",
                            "0347": "RN Tamizaje - Toxo IgM (enumeration) ['-','+','no se hizo']",
                            "0290": "Código operatorio (code)",
                            "0310": "RN Sexo (enumeration) ['femenino','masculino','no definido']",
                            "0325": "RN Reanimación - Máscara (enumeration) ['no','si']",
                            "0378": "BCG (enumeration) ['no','si']",
                            "0336": "Enfermedades RN (enumeration) ['1 o más','ninguna']",
                            "0395": "Peso RN al egreso (numeric)",
                            "0343": "RN Tamizaje - VDRL (enumeration) ['-','+','no se hizo']",
                            "0283": "Hora nacimiento (time)",
                            "0329": "Fallece lugar de parto (enumeration) ['no','si']",
                            "0370": "Egreso RN - hora (time)",
                            "0320": "RN Peso para Edad Gestacional (enumeration) ['adecuado','pequeño','grande']",
                            "0371": "Egreso RN (enumeration) ['vivo','fallece','traslado']",
                            "0282": "Nacimiento (enumeration) ['vivio','muerto ante parto','muerto parto','muerto ignora momento']",
                            "0377": "Boca arriba (enumeration) ['no','si']",
                            "0293": "Desgarros (no) (boolean)",
                            "0425": "Egreso RN - fecha (date)",
                            "0331": "Atendió Parto (enumeration) ['medico','obstetra','enfermera','auxiliar','estudiante','empirica','otro','pediatra']",
                            "0346": "RN Tamizaje - Bilirrubina (enumeration) ['-','+','no se hizo']",
                            "0335": "Defectos congénitos (enumeration) ['no','menor','mayor','si']",
                            "0324": "RN Reanimación - Aspiración (enumeration) ['no','si']",
                            "0313": "Perimetro cefálico (numeric)",
                            "0327": "RN Reanimación - Masaje (enumeration) ['no','si']",
                            "0376": "Alimento al alta (enumeration) ['lactancia exclusiva','parcial','artificial']",
                            "0296": "Ocitócicos postalumbramiento (enumeration) ['no','si']",
                            "0323": "RN Reanimación - Estimulación (enumeration) ['no','si']",
                            "0316": "Edad gestacional RN - días (numeric)",
                            "0292": "Episiotomía (enumeration) ['no','si']",
                            "0388": "Nro. Historia RN (text)",
                            "0345": "RN Tamizaje - Hbpatía (enumeration) ['-','+','no se hizo']",
                            "0298": "Placenta retenida (enumeration) ['no','si']",
                            "0287": "Terminación (enumeration) ['vaginal espontánea','cesárea','fórceps','vacuum','otra']",
                            "0291": "Posición parto (enumeration) ['sentada','cuclillas','acostada']",
                            "0333": "Atendió Neonato (enumeration) ['medico','obstetra','enfermera','auxiliar','estudiante','empirica','otro','pediatra']",
                            "0326": "RN Reanimación - Oxígeno (enumeration) ['no','si']",
                            "0348": "RN Tamizaje - Meconio 1er. día (enumeration) ['no','si']",
                            "0311": "Peso al nacer (numeric)",
                            "0322": "Apgar 5to. Minuto (numeric)",
                            "0315": "Edad gestacional RN (numeric)",
                            "0330": "Referido (enumeration) ['alojamiento conjunto','neonatología','otro hospital']",
                            "0284": "Fecha de nacimiento (date)",
                            "0389": "Nombre RN (text)",
                            "0373": "Fallece lugar de traslado (enumeration) ['no','si','sin dato']",
                            "0295": "Ocitócicos prealumbramiento (enumeration) ['no','si']",
                            "0328": "RN Reanimación - Tubo (enumeration) ['no','si']",
                            "0344": "RN Tamizaje - Cardiov (enumeration) ['-','+','no se hizo']"
                          }
                        },
                        "0533": "PaO2/FiO2 < 200 mmHg (enumeration) ['no','si']",
                        "0518": "Respiración jadeante (gasping) (enumeration) ['no','si']",
                        "0522": "Alteraciones de la coagulación (enumeration) ['no','si']",
                        "0529": "Creatinina >= 300 micromoles/l ó >= 3.5 mg/dl (enumeration) ['no','si']",
                        "0503": "Administración >= 3 vol. hemoderivados (enumeration) ['no','si']",
                        "0552": "Histerectomía (enumeration) ['no','si']",
                        "0530": "Bilirubina > 100 moles/l ó > 6.0 mg/dl (enumeration) ['no','si']",
                        "0523": "Coma (enumeration) ['no','si']",
                        "0517": "Cianosis aguda (enumeration) ['no','si']",
                        "0528": "Plaquetas < 50.000 por ml (enumeration) ['no','si']",
                        "0642": "Variables para identificar casos de Near Miss (enumeration) ['no','si']",
                        "0520": "Bradipnea severa (FR< 6 rpm) (enumeration) ['no','si']",
                        "0534": "Lactato > 5 micromoles/l o 45 mg/dl (enumeration) ['no','si']",
                        "0531": "pH < 7.1 (enumeration) ['no','si']",
                        "0527": "Parálisis generalizada (enumeration) ['no','si']",
                        "0516": "Ictericia en preeclampsia (enumeration) ['no','si']",
                        "0548": "Administración continua de agentes vasoactivos (enumeration) ['no','si']",
                        "0639": "Ingreso a UCI >= 7 días (enumeration) ['no','si']",
                        "0524": "Inconsciencia prolongada > 12 hs (enumeration) ['no','si']",
                        "0554": "Reanimación cardio-pulmonar (enumeration) ['no','si']",
                        "0519": "Traquipnea severa (FR > 40 rpm) (enumeration) ['no','si']",
                        "0532": "pO2 < 90% >= 1 hora (enumeration) ['no','si']",
                        "0521": "Oliguria resistente a líquidos diuréticos (enumeration) ['no','si']",
                        "0515": "Paro cardíaco (enumeration) ['no','si']",
                        "0514": "Shock (enumeration) ['no','si']",
                        "0526": "Convulsiones incontrolables / estado de mal epiléptico (enumeration) ['no','si']",
                        "0550": "Intubación y ventilación no relacionada con la anestesia (enumeration) ['no','si']",
                        "0553": "Diálisis en caso de IRA (enumeration) ['no','si']",
                        "0525": "Accidente cerebro vascular (enumeration) ['no','si']",
                        "0398": "Libre 2 (text)",
                        "0400": "Libre 4 (text)",
                        "0399": "Libre 3 (text)",
                        "0396": "Libre 0 (text)",
                        "0397": "Libre 1 (text)",
                        "0591": "Bacteriuria asintomática (enumeration) ['no','si']",
                        "0564": "TVP (enumeration) ['no','si']",
                        "0575": "Semana Influenza (numeric)",
                        "0507": "Acretismo placentario (enumeration) ['no','si']",
                        "0410": "Gamma globulina anti D (enumeration) ['no','si','n/c']",
                        "0542": "Ligaduras hemostáticas de las arterias uterinas/hipogástricas (enumeration) ['no','si']",
                        "0444": "Sulfato Mg en Eclampsia (enumeration) ['no','si']",
                        "0645": "Suturas B-Lynch o similares (enumeration) ['no','si']",
                        "0498": "Síndrome Hellp (enumeration) ['no','si']",
                        "0615": "Embolia L.A. (enumeration) ['no','si']",
                        "0438": "TDP - Prueba VIH (enumeration) ['negativo','positivo','n/r','n/c']",
                        "0073": "Drogas 3er. (enumeration) ['no','si']",
                        "0433": "Tamizaje Antenatal - Prueba VIH <20 sem. (enumeration) ['positivo','negativo','n/c','s/d']",
                        "0604": "Diabetes Mellitus (enumeration) ['no','si']",
                        "0652": "Hipertensión gestacional (enumeration) ['no','si']",
                        "0619": "Alteración del estado de conciencia (enumeration) ['no','si']",
                        "0063": "Drogas 1er. (enumeration) ['no','si']",
                        "0563": "TEP (enumeration) ['no','si']",
                        "0599": "Atonía uterina (enumeration) ['no','si']",
                        "0614": "Hiperemesis gravídica (enumeration) ['no','si']",
                        "0437": "TDP - Prueba Sífilis (enumeration) ['negativo','positivo','n/r','n/c']",
                        "0648": "Colestasis (enumeration) ['no','si']",
                        "0608": "D.M. gestacional (enumeration) ['no','si']",
                        "0595": "Infección herida cesárea (enumeration) ['no','si']",
                        "0070": "Violencia 2do. (enumeration) ['no','si']",
                        "0626": "Otros trastornos - resumen (enumeration) ['no','si']",
                        "0631": "Oligoamnios (enumeration) ['no','si']",
                        "0637": "Traje antishock no neumático (enumeration) ['no','si']",
                        "0646": "Otra complicación obstétrica (enumeration) ['no','si']",
                        "0635": "Via venosa central (enumeration) ['no','si','s/d']",
                        "0544": "Ingreso a UCI (enumeration) ['no','si','s/d']",
                        "0443": "Sulfato Mg en Preeclampsia (enumeration) ['no','si']",
                        "0632": "Polihidramnio (enumeration) ['no','si']",
                        "0421": "Prueba sífilis treponémica >= 20s (enumeration) ['negativo','positivo','se desconoce','no corresponde']",
                        "0067": "Fumadora pasiva 2do. (enumeration) ['no','si']",
                        "0603": "Trastornos metabólicos (enumeration) ['no','si']",
                        "0574": "Fecha Influenza (date)",
                        "0512": "Crisis tiroidea (enumeration) ['no','si']",
                        "0598": "Mola hidatiforme (enumeration) ['no','si']",
                        "0432": "Antecedentes VIH + (enumeration) ['no','si']",
                        "0601": "Restos (enumeration) ['no','si']",
                        "0506": "Placenta previa (enumeration) ['no','si']",
                        "0620": "Anemia (enumeration) ['no','si']",
                        "0570": "Tdap (enumeration) ['no','si, previa embarazo','si, durante embarazo','si, postparto/aborto']",
                        "0653": "Hipertensión crónica + PE sobreimpuesta (enumeration) ['no','si']",
                        "0440": "VIH en RN - Expuesto (enumeration) ['no','si','s/d']",
                        "0409": "Embarazo Ectópico - antecedentes (numeric)",
                        "0573": "Influenza (enumeration) ['no','si, previa embarazo','si, durante embarazo','si, postparto/aborto']",
                        "0623": "Neoplasia maligna (enumeration) ['no','si']",
                        "0607": "D.M. no insulinodependiente previa (enumeration) ['no','si']",
                        "0062": "Fumadora pasiva 1er. (enumeration) ['no','si']",
                        "0439": "TDP - ARV (enumeration) ['no','si','n/c']",
                        "0436": "Tamizaje Antenatal - TARV VIH >=20 sem. (enumeration) ['no','si','n/c']",
                        "0500": "Endometritis (enumeration) ['no','si']",
                        "0629": "Parto obstruido (enumeration) ['no','si']",
                        "0618": "Convulsiones (enumeration) ['no','si']",
                        "0415": "Prueba sífilis treponémica < 20s (enumeration) ['negativo','positivo','se desconoce','no corresponde']",
                        "0066": "Fumadora activa 2do. (enumeration) ['no','si']",
                        "0509": "Rotura uterina (enumeration) ['no','si']",
                        "0566": "Otras infecciones (enumeration) ['no','si']",
                        "0625": "Otros trastornos (enumeration) ['no','si']",
                        "0636": "Embolizaciones (enumeration) ['no','si']",
                        "0472": "Egreso materno - hora (time)",
                        "0424": "Tratamiento sífilis pareja >= 20s (enumeration) ['no','si','se desconoce','no corresponde']",
                        "0474": "Autopsia (enumeration) ['no','si']",
                        "0505": "Embarazo ectópico - hemorragia (enumeration) ['no','si']",
                        "0606": "D.M. insulinodependiente previa (enumeration) ['no','si']",
                        "0617": "Valvulopatía (enumeration) ['no','si']",
                        "0633": "Sufrimiento fetal agudo (enumeration) ['no','si']",
                        "0468": "MAC - EQV femenino - accedido (boolean)",
                        "0418": "Tratamiento sífilis pareja < 20s (enumeration) ['no','si','se desconoce','no corresponde']",
                        "0540": "Administración de hemoderivados (enumeration) ['no','si','s/d']",
                        "0610": "Hipotiroidismo (enumeration) ['no','si']",
                        "0602": "Defecto de coagulación (enumeration) ['no','si']",
                        "0650": "Hipertensión crónica (enumeration) ['no','si']",
                        "0072": "Fumadora pasiva 3er. (enumeration) ['no','si']",
                        "0499": "Pielonefritis (enumeration) ['no','si']",
                        "0628": "Complicaciones obstétricas (enumeration) ['no','si']",
                        "0091": "Tamizaje Antenatal - VIH <20 sem. solicitado (enumeration) ['no','si','n/c']",
                        "0571": "Fecha Tdap (date)",
                        "0068": "Drogas 2do. (enumeration) ['no','si']",
                        "0419": "Semana prueba sífilis No trepon. >= 20s (numeric)",
                        "0484": "Oliguria (enumeration) ['no','si']",
                        "0624": "Trastorno siquiátrico (enumeration) ['no','si']",
                        "0621": "Anemia falciforme (enumeration) ['no','si']",
                        "0075": "Violencia 3er. (enumeration) ['no','si']",
                        "0473": "Tipo de egreso (enumeration) ['egreso médico','fallece','contra consejo médico','fuga','alta solicitada','alta hospitalaria']",
                        "0508": "DPPNI (enumeration) ['no','si']",
                        "0435": "Tamizaje Antenatal - Prueba VIH >=20 sem. (enumeration) ['positivo','negativo','n/c','s/d']",
                        "0065": "Violencia 1er.   (enumeration) ['no','si']",
                        "0609": "Trastornos tiroideos (enumeration) ['no','si']",
                        "0596": "Infección episiorrafia (enumeration) ['no','si']",
                        "0611": "Hipertiroidismo (enumeration) ['no','si']",
                        "0504": "Hemorragia post-aborto (enumeration) ['no','si']",
                        "0651": "Pre eclampsia severa (enumeration) ['no','si']",
                        "0423": "Tratamiento sífilis >= 20s (enumeration) ['no','si','se desconoce','no corresponde']",
                        "0543": "Laparotomía (excluye cesárea) (enumeration) ['no','si','s/d']",
                        "0069": "Alcohol 2do. (enumeration) ['no','si']",
                        "0605": "Tolerancia oral a la glucosa anormal (enumeration) ['no','si','no se hizo']",
                        "0565": "Neumonia (enumeration) ['no','si']",
                        "0537": "Uterotónicos para tto. hemorragia (enumeration) ['no','si','s/d']",
                        "0600": "Desgarros (enumeration) ['no','si']",
                        "0572": "Semana Tdap (numeric)",
                        "0546": "Uso de ATB IV para tto. de complicación infecciosa (enumeration) ['no','si','s/d']",
                        "0502": "Sepsis (enumeration) ['no','si']",
                        "0434": "Tamizaje Antenatal - TARV VIH <20 sem. (enumeration) ['no','si','n/c']",
                        "0622": "Enfermedad renal (enumeration) ['no','si']",
                        "0638": "Balones hidrostáticos (enumeration) ['no','si']",
                        "0074": "Alcohol 3er. (enumeration) ['no','si']",
                        "0061": "Fumadora activa 1er. (enumeration) ['no','si']",
                        "0064": "Alcohol 1er. (enumeration) ['no','si']",
                        "0536": "Alumbramiento manual (enumeration) ['no','si','s/d']",
                        "0071": "Fumadora activa 3er. (enumeration) ['no','si']",
                        "0590": "Infecciones (enumeration) ['no','si']",
                        "0649": "Corioamnionitis (enumeration) ['no','si']",
                        "0413": "Semana prueba sífilis No trepon. < 20s (numeric)",
                        "0303": "Anestesia local (enumeration) ['no','si']",
                        "0199": "Edad gestacional - días (numeric)",
                        "0059": "EG confiable por FUM (enumeration) ['no','si']",
                        "0275": "Hemorragia 3er. trim. (enumeration) ['no','si']",
                        "0261": "Eclampsia (enumeration) ['no','si']",
                        "0029": "Antecedentes Eclampsia (personales) (enumeration) ['no','si']",
                        "0205": "Acompañante Parto (enumeration) ['pareja','familiar','otro','ninguno']",
                        "0095": "Hb<20 sem. (numeric)",
                        "0115": "Tratamiento Sífilis < 20s (enumeration) ['no','si','se desconoce','no corresponde']",
                        "0108": "Glucemia >=30 sem. (numeric)",
                        "0110": "Preparación parto (enumeration) ['no','si']",
                        "0104": "Bacteriuria >=20 sem. (enumeration) ['normal','anormal','no se hizo']",
                        "0190": "Inicio parto (enumeration) ['espontáneo','inducido','cesárea electiva','cesárea emergencia']",
                        "0081": "Examen mamas normal (enumeration) ['no','si']",
                        "0111": "Consejería lactancia (enumeration) ['no','si']",
                        "0183": "Fecha de ingreso (date)",
                        "0017": {
                          "countryId": "",
                          "divisionId": "",
                          "subdivisionId": "",
                          "code": ""
                        },
                        "0202": "Presentación situación (enumeration) ['cefálica','pelviana','transversa','n/a']",
                        "0041": "Abortos (numeric)",
                        "0030": "Otro antecedente familiar (enumeration) ['no','si']",
                        "0186": "Hospitalización (enumeration) ['no','si']",
                        "0003": "Domicilio (text)",
                        "0101": "Tamizaje Antenatal - Chagas (enumeration) ['-','+','no se hizo']",
                        "0088": "Tamizaje Antenatal - Toxoplasmosis < 20 sem. (enumeration) ['-','+','no se hizo']",
                        "0060": "EG confiable por Eco < 20s (enumeration) ['no','si']",
                        "0099": "Hb>=20 sem. (numeric)",
                        "0383": "Fallece durante traslado (enumeration) ['no','si']",
                        "0044": "RN que viven (numeric)",
                        "0302": "Analgesia (enumeration) ['no','si']",
                        "0055": "Peso anterior (numeric)",
                        "0010": "Edad materna <15 o >35 (boolean)",
                        "0090": "Tamizaje Antenatal - Toxoplasmosis 1er. Consulta (enumeration) ['-','+','no se hizo']",
                        "0013": "Estudios (enumeration) ['ninguno','primaria','secundaria','universidad','técnica/vocacional','educación especial']",
                        "0201": "Edad gestacional al parto - por ECO (boolean)",
                        "0109": "Tamizaje Antenatal - Estreptococo B (enumeration) ['-','+','no se hizo']",
                        "0040": "Gestas previas (numeric)",
                        "0033": "Antecedentes Infertilidad (enumeration) ['no','si']",
                        "0023": "Antecedentes Diabetes (personales) (enumeration) ['no','tipo I','tipo II','tipo G']",
                        "0051": "Fecha embarazo anterior (date)",
                        "0034": "Antecedentes Cardiopatía (enumeration) ['no','si']",
                        "0182": "Parto / Aborto (enumeration) ['parto','aborto']",
                        "0022": "Antecedentes Diabetes (familiares) (enumeration) ['no','si']",
                        "0114": "Prueba Sífilis No treponémica >= 20s (enumeration) ['negativo','positivo','se desconoce']",
                        "0056": "Talla madre (numeric)",
                        "0185": "Consultas prenatales (numeric)",
                        "0016": "Vive sola (enumeration) ['no','si']",
                        "0009": "Edad materna (numeric)",
                        "0005": "Teléfono (text)",
                        "0087": "Inmunización (enumeration) ['no','si']",
                        "0098": "Folatos (enumeration) ['no','si']",
                        "0026": "Antecedentes Preclampsia (familiares) (enumeration) ['no','si']",
                        "0048": "Ant. nacidos muertos (numeric)",
                        "0260": "Preeclampsia leve (enumeration) ['no','si']",
                        "0382": "Condición al egreso (enumeration) ['sana','fallece','con patología','traslado/NA']",
                        "0089": "Tamizaje Antenatal - Toxoplasmosis >= 20 sem. (enumeration) ['-','+','no se hizo']",
                        "0054": "Fracaso método anticonceptivo (enumeration) ['no usaba','barrera','DIU','hormona','emergencia','natural','inyectable','SIU']",
                        "0200": "Edad gestacional al parto - por FUM (boolean)",
                        "0043": "Ant. nacidos vivos (numeric)",
                        "0305": "Anestesia general (enumeration) ['no','si']",
                        "0285": "Embarazo múltiple (enumeration) ['no','si']",
                        "0004": "Localidad (text)",
                        "0049": "Ant. muertos 1a. sem. (numeric)",
                        "0258": "Trastornos hipertensivos (enumeration) ['no','si']",
                        "0027": "Antecedentes Preclampsia (personales) (enumeration) ['no','si']",
                        "0015": "Estado civil (enumeration) ['casada','unión estable','soltero','otro','divorciada','concubinato','comprometida','anulada','separada','legalmente separada','viuda','solo visitas']",
                        "0274": "Hemorragia 2do. trim. (enumeration) ['no','si']",
                        "0038": "Ultimo RN previo (enumeration) ['no sabe','< 2500g','normal','> 4000g']",
                        "0012": "Alfabeta (enumeration) ['no','si']",
                        "0032": "Antecedentes Cirugía genito-urinaria (enumeration) ['no','si']",
                        "0204": "Acompañante TDP (enumeration) ['pareja','familiar','otro','ninguno']",
                        "0080": "Examen odontológico normal (enumeration) ['no','si']",
                        "0039": "Antecedentes gemelares (enumeration) ['no','si']",
                        "0191": "Ruptura de membranas (enumeration) ['no','si']",
                        "0103": "Bacteriuria <20 sem. (enumeration) ['normal','anormal','no se hizo']",
                        "0021": "Antecedentes TBC (personales) (enumeration) ['no','si']",
                        "0057": "Fecha última menstruación (date)",
                        "0097": "Hierro (enumeration) ['no','si']",
                        "0024": "Antecedentes Hipertensión (familiares) (enumeration) ['no','si']",
                        "0046": "Partos previos (numeric)",
                        "0035": "Antecedentes Nefropatía (enumeration) ['no','si']",
                        "0086": "Rh (enumeration) ['+','-']",
                        "0301": "Antibióticos (enumeration) ['no','si']",
                        "0198": "Edad gestacional al parto (numeric)",
                        "0304": "Anestesia regional (enumeration) ['no','si']",
                        "0031": "Otro antecedente personal (enumeration) ['no','si']",
                        "0188": "Corticoides (enumeration) ['completo','incompleto','ninguna','n/c','multiples']",
                        "0385": "Anticoncepcion consejeria (enumeration) ['ninguna','oral','escrita','no','si']",
                        "0273": "Hemorragia 1er. trim. (enumeration) ['no','si']",
                        "0050": "Ant. muertos después 1a. sem. (numeric)",
                        "0203": "Tamaño fetal acorde (enumeration) ['no','si']",
                        "0053": "Embarazo planeado (enumeration) ['no','si']",
                        "0184": "Carné (enumeration) ['no','si']",
                        "0093": "Tamizaje Antenatal - VIH >=20 sem. solicitado (enumeration) ['no','si','n/c']",
                        "0028": "Antecedentes Eclampsia (familiares) (enumeration) ['no','si']",
                        "0379": "Fecha de egreso materno (date)",
                        "0042": "Partos vaginales (numeric)",
                        "0102": "Tamizaje Antenatal - Malaria (enumeration) ['-','+','no se hizo']",
                        "0306": "Transfusión (enumeration) ['no','si']",
                        "0036": "Antecedentes Violencia (enumeration) ['no','si']",
                        "0105": "Glucemia <  20 sem. (numeric)",
                        "0112": "Prueba Sífilis No treponémica < 20s (enumeration) ['negativo','positivo','se desconoce']",
                        "0085": "Grupo sanguíneo (text)",
                        "0300": "Ocitócicos en TDP (enumeration) ['no','si']",
                        "0058": "Fecha probable de parto (date)",
                        "0047": "Cesáreas (numeric)",
                        "0018": {
                          "countryId": "",
                          "divisionId": "",
                          "subdivisionId": "",
                          "code": ""
                        },
                        "0025": "Antecedentes Hipertensión (personales) (enumeration) ['no','si']",
                        "0020": "Antecedentes TBC (familiares) (enumeration) ['no','si']",
                        "prenatal": {
                          "1": {
                            "line_id": "",
                            "0121": "PA sistólica (numeric)",
                            "0119": "Edad gestacional (numeric)",
                            "0394": "PA diastólica (numeric)",
                            "0116": "Fecha consulta (date)",
                            "0120": "Peso (numeric)"
                          },
                          "2": {
                            "line_id": "",
                            "0121": "PA sistólica (numeric)",
                            "0119": "Edad gestacional (numeric)",
                            "0122": "Altura uterina (numeric)",
                            "0125": "Movimientos fetales (code)",
                            "0394": "PA diastólica (numeric)",
                            "0116": "Fecha consulta (date)",
                            "0124": "FCF (lpm) (numeric)",
                            "0120": "Peso (numeric)"
                          }
                        }
                      }
                    },
                    "0011": "Etnia (enumeration) ['blanca','indígena','mestiza','negra','otra','amarilla','afro','caucásica','china','east indian','mezcla-african/east indian','portuguesa','siria/libanés','no se indica','hispano','descendiente indio','desconocido']",
                    "0002": "Apellido (text)",
                    "0006": "Fecha de nacimiento madre (date)",
                    "0019": "Número de identificación (text)"
                  }

